# Generated by Django 3.1.6 on 2021-02-08 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medic',
            fields=[
                ('medic_id', models.IntegerField(primary_key=True, serialize=False)),
                ('medic_name', models.CharField(max_length=255)),
                ('medic_type', models.CharField(max_length=25)),
                ('medic_position', models.CharField(max_length=30)),
                ('medic_remuneration', models.IntegerField()),
                ('hospital_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.hospital')),
            ],
        ),
    ]
