# Generated by Django 3.1 on 2020-08-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea_3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='number',
            field=models.CharField(max_length=3, unique=True, verbose_name='Número'),
        ),
    ]
